spring:
#设定ftl文件路径
  freemarker:
    template-loader-path: classpath:/templates/
    #设定静态文件路径，js,css等
  resources:
    static-locations: classpath:/static/
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
server:
  port: 8012